spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: nubiformstudio@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true